import type { Metadata } from "next";
import "./globals.css";
import { Footer, NavBar } from "@/components";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Tutor Dunia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased text-text bg-[#f7f7f7] max-w-[1024px] mx-auto`}
      >
        <NavBar />
        {children}
        <Footer />
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
      </body>
    </html>
  );
}
